version: '3'
services:
  oz-server:
    tty: true
    build: ./oz-server
    ports:
      - "8080:8080"
    volumes:
      - ./oz-server:/usr/src/app/oz-server
    command: gunicorn app:__hug_wsgi__ --reload -b 0.0.0.0:8080
