version: '3'
services:
  oz-server:
    tty: true
    build: ./oz-server
    ports:
      - "8080:8080"
    volumes:
      - ./oz-server:/usr/src/app/oz-server
      - ./oz-server/.flair:/home/oz/.flair
    command: gunicorn app:__hug_wsgi__ --reload -b 0.0.0.0:8080 --timeout 600

  rasa_nlu:
      image: rasa/rasa_nlu:latest-tensorflow
      ports:
        - "5000:5000"
      volumes:
        - ./rasa_models/rasa_nlu:/app/models
      command:
        - start
        - --path
        - models
        - --port
        - "5000"
